<a href="https://colab.research.google.com/github/Keistkmiya/Tugas2-MachineLearning/blob/main/Tugas2_Chapter1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 1: Vectors, Matrices, and Arrays

## Setup and Library Imports

In [1]:
!pip install mglearn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 581.4/581.4 kB 9.0 MB/s eta 0:00:00


In [2]:
import numpy as np
import pandas as pd
import mglearn
import warnings

warnings.filterwarnings("ignore")

## Creating a Vector

Untuk merepresentasikan data numerik satu dimensi (seperti sebuah baris atau kolom angka tunggal), kita bisa menggunakan struktur data array dari NumPy untuk membuat sebuah vektor. Kita bisa membuat vektor dalam bentuk baris mendatar (row vector) maupun kolom menurun (column vector).

In [31]:
vector_row = np.array([1, 2, 3])
vector_column = np.array([[1],
                          [2],
                          [3]])

print("Bentuk Vektor Baris:\n", vector_row)
print("\nBentuk Vektor Kolom:\n", vector_column)

Bentuk Vektor Baris:
 [1 2 3]

Bentuk Vektor Kolom:
 [[1]
 [2]
 [3]]


## Creating a Matrix

Jika vektor adalah struktur data satu dimensi, matriks adalah struktur data dua dimensi yang terdiri dari baris dan kolom. Kita bisa membuat matriks di NumPy dengan menyusun array di dalam array (nested lists). Matriks ini akan sangat sering kita gunakan, terutama untuk merepresentasikan dataset di mana baris adalah jumlah data, dan kolom adalah fitur-fiturnya.

In [4]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Bentuk Matriks:\n", matrix)

Bentuk Matriks:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Creating a Sparse Matrix

Dalam *machine learning*, kita sering berhadapan dengan kumpulan data yang ukurannya sangat besar, namun sebagian besar isinya bernilai nol (misalnya pada representasi *bag-of-words* untuk data teks). Menyimpan semua angka nol tersebut di dalam memori akan sangat membebani komputer.

Untuk mengatasinya, kita menggunakan *Sparse Matrix*. Struktur data ini sangat efisien karena hanya mengingat dan menyimpan lokasi elemen yang memiliki nilai selain nol.

In [30]:
from scipy import sparse

matrix_large = np.array([[0, 0],
                         [0, 1],
                         [3, 0]])
matrix_sparse = sparse.csr_matrix(matrix_large)

print("Matriks Asli (Dense):\n", matrix_large)
print("\nMatriks Sparse:\n", matrix_sparse)

Matriks Asli (Dense):
 [[0 0]
 [0 1]
 [3 0]]

Matriks Sparse:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (3, 2)>
  Coords	Values
  (1, 1)	1
  (2, 0)	3


## Selecting Elements

Setelah kita membuat vektor atau matriks, sering kali kita perlu mengambil satu elemen spesifik atau sekumpulan elemen tertentu dari dalam susunan data tersebut. Proses ini disebut dengan *indexing* dan *slicing*.

Satu hal yang sangat penting untuk kita (dan adik tingkat nanti) ingat terus: indeks dalam bahasa pemrograman Python selalu dimulai dari angka 0, bukan 1!

In [29]:
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Elemen ketiga dari vektor:", vector[2])
print("Semua elemen vektor setelah elemen ketiga:", vector[3:])
print("Elemen pada baris kedua, kolom ketiga dari matriks:", matrix[1, 2])
print("Semua elemen pada baris pertama matriks:\n", matrix[0, :])

Elemen ketiga dari vektor: 3
Semua elemen vektor setelah elemen ketiga: [4 5 6]
Elemen pada baris kedua, kolom ketiga dari matriks: 6
Semua elemen pada baris pertama matriks:
 [1 2 3]


## Describing a Matrix

Ketika kita berhadapan dengan dataset yang sangat besar, kita harus bisa mengecek karakteristik dari struktur datanya dengan cepat. NumPy menyediakan beberapa atribut dasar yang sangat berguna untuk hal ini, yaitu `shape` (untuk melihat jumlah baris dan kolom), `size` (untuk melihat total seluruh elemen), dan `ndim` (untuk melihat jumlah dimensi dari array tersebut).

In [8]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Shape dari matriks (baris, kolom):", matrix.shape)
print("Total keseluruhan elemen (size):", matrix.size)
print("Jumlah dimensi (ndim):", matrix.ndim)

Shape dari matriks (baris, kolom): (3, 4)
Total keseluruhan elemen (size): 12
Jumlah dimensi (ndim): 2


## Applying Operations to Elements

Ada kalanya kita ingin menerapkan sebuah fungsi (seperti rumus matematika sederhana) ke setiap elemen di dalam array kita tanpa harus menggunakan perulangan (looping) yang memakan waktu lama. Kita bisa menggunakan fitur `vectorize` dari NumPy. Fitur ini memungkinkan kita mengubah sebuah fungsi dasar di Python agar dapat langsung memproses seluruh isi matriks sekaligus.

In [28]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
add_100 = lambda i: i + 100
vectorized_add_100 = np.vectorize(add_100)

print("Matriks setelah ditambahkan 100:\n", vectorized_add_100(matrix))

Matriks setelah ditambahkan 100:
 [[101 102 103]
 [104 105 106]
 [107 108 109]]


## Finding the Maximum and Minimum Values

Sering kali, Kita perlu mengetahui nilai tertinggi dan terendah di dalam sebuah array atau matriks. NumPy memiliki fungsi bawaan `max` dan `min` untuk melakukan hal tersebut. Selain itu, kita juga bisa menggunakan parameter `axis` untuk membatasi pencarian hanya di sepanjang baris tertentu atau kolom tertentu.

In [10]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Nilai maksimum dari seluruh matriks:", np.max(matrix))
print("Nilai minimum dari seluruh matriks:", np.min(matrix))
print("Nilai maksimum di setiap kolom (axis=0):", np.max(matrix, axis=0))
print("Nilai maksimum di setiap baris (axis=1):", np.max(matrix, axis=1))

Nilai maksimum dari seluruh matriks: 9
Nilai minimum dari seluruh matriks: 1
Nilai maksimum di setiap kolom (axis=0): [7 8 9]
Nilai maksimum di setiap baris (axis=1): [3 6 9]


## Calculating Average, Variance, and Standard Deviation

Untuk mendapatkan gambaran deskriptif dari sebuah data, Kita sering kali perlu menghitung nilai rata-rata (mean), varians (variance), dan standar deviasi (standard deviation). NumPy menyediakan fungsi bawaan yang dirancang khusus untuk menghitung ketiga metrik statistik tersebut secara langsung pada seluruh elemen array maupun pada sumbu (axis) tertentu.

In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Rata-rata (Mean):", np.mean(matrix))
print("Varians (Variance):", np.var(matrix))
print("Standar Deviasi (Standard Deviation):", np.std(matrix))
print("Rata-rata setiap kolom (axis=0):", np.mean(matrix, axis=0))

Rata-rata (Mean): 5.0
Varians (Variance): 6.666666666666667
Standar Deviasi (Standard Deviation): 2.581988897471611
Rata-rata setiap kolom (axis=0): [4. 5. 6.]


## Reshaping Arrays

Sering kali kita perlu mengubah bentuk (dimensi) dari sebuah array tanpa mengubah isi data di dalamnya. Misalnya, kita ingin mengubah matriks berukuran 4x3 menjadi matriks berukuran 2x6. Untuk melakukan hal ini secara efisien, kita menggunakan fungsi `reshape` dari NumPy.

Syarat utama dari fungsi ini adalah jumlah total elemen pada bentuk yang baru harus sama persis dengan jumlah total elemen pada bentuk yang lama.

In [27]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9],
                   [10, 11, 12]])
reshaped_matrix = matrix.reshape(2, 6)

print("Matriks Asli (4 baris, 3 kolom):\n", matrix)
print("\nMatriks Baru (2 baris, 6 kolom):\n", reshaped_matrix)

Matriks Asli (4 baris, 3 kolom):
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Matriks Baru (2 baris, 6 kolom):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


## Transposing a Vector or Matrix

Untuk menukar posisi baris menjadi kolom (dan sebaliknya), kita menggunakan metode transpos. Hal ini sangat sering kita lakukan, terutama ketika kita harus menyesuaikan orientasi matriks agar sesuai dengan syarat operasi aljabar linier, seperti perkalian antarmatriks. Di NumPy, transposisi matriks dapat dilakukan dengan sangat mudah menggunakan atribut `.T`.

In [13]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriks Asli:\n", matrix)
print("\nMatriks Transpos:\n", matrix.T)

Matriks Asli:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriks Transpos:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Flattening a Matrix

Sering kali kita perlu mengubah matriks multidimensi menjadi satu baris vektor yang panjang (satu dimensi). Proses ini disebut dengan *flattening*. Salah satu kegunaan utamanya adalah ketika kita ingin memasukkan data dari matriks ke dalam algoritma yang hanya menerima input dalam bentuk vektor satu dimensi. Di NumPy, kita bisa menggunakan metode `flatten` untuk melakukan hal ini.

In [14]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriks Asli:\n", matrix)
print("\nMatriks Setelah Di-flatten:", matrix.flatten())

Matriks Asli:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matriks Setelah Di-flatten: [1 2 3 4 5 6 7 8 9]


## Finding the Rank of a Matrix

Rank dari sebuah matriks memberikan informasi tentang jumlah dimensi independen secara linier dalam matriks tersebut. Mengetahui rank sangat penting ketika kita ingin menyelesaikan sistem persamaan linier atau saat melakukan reduksi dimensi. Di NumPy, kita bisa menggunakan fungsi `matrix_rank` dari modul aljabar linier (`linalg`) untuk mendapatkan nilai ini dengan cepat.

In [15]:
matrix = np.array([[1, 1, 1],
                   [1, 1, 10],
                   [1, 1, 15]])

print("Matriks:\n", matrix)
print("\nRank Matriks:", np.linalg.matrix_rank(matrix))

Matriks:
 [[ 1  1  1]
 [ 1  1 10]
 [ 1  1 15]]

Rank Matriks: 2


## Calculating the Determinant

Determinant adalah nilai skalar yang bisa dihitung dari elemen-elemen matriks persegi. Nilai ini sangat berguna bagi kita untuk menentukan apakah suatu matriks memiliki invers. Jika determinannya nol, maka matriks tersebut disebut matriks singular dan tidak memiliki invers. Di NumPy, kita cukup menggunakan fungsi `det` dari modul `linalg`.

In [16]:
matrix = np.array([[1, 2, 3],
                   [2, 4, 6],
                   [3, 8, 9]])

print("Matriks:\n", matrix)
print("\nDeterminan Matriks:", np.linalg.det(matrix))

Matriks:
 [[1 2 3]
 [2 4 6]
 [3 8 9]]

Determinan Matriks: 0.0


## Getting the Diagonal of a Matrix

Terkadang kita hanya tertarik pada elemen-elemen yang berada di diagonal utama sebuah matriks. Hal ini sering terjadi dalam berbagai algoritma aljabar linier atau saat kita berhadapan dengan matriks korelasi. Untuk mengambil nilai-nilai tersebut, kita bisa menggunakan fungsi `diagonal` dari NumPy.

In [17]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriks:\n", matrix)
print("\nElemen-elemen Diagonal Utama:", matrix.diagonal())

Matriks:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Elemen-elemen Diagonal Utama: [1 5 9]


## Calculating the Trace of a Matrix

Trace adalah jumlah dari seluruh elemen pada diagonal utama sebuah matriks persegi. Kita bisa menggunakan metode `trace` dari NumPy untuk mendapatkan hasil penjumlahan tersebut dengan sangat cepat. Ini adalah cara yang lebih efisien daripada kita harus mengambil diagonalnya terlebih dahulu kemudian menjumlahkannya secara manual.

In [19]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Matriks:\n", matrix)
print("\nTrace Matriks (Jumlah Diagonal):", matrix.trace())

Matriks:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Trace Matriks (Jumlah Diagonal): 15


## Finding Eigenvalues and Eigenvectors

Eigenvalues dan eigenvectors adalah konsep inti dalam aljabar linier yang sering kita gunakan dalam algoritma machine learning, terutama untuk teknik reduksi dimensi. Eigenvectors mewakili arah penyebaran data, sedangkan eigenvalues mewakili besarnya penyebaran tersebut di arah tersebut. Kita bisa mendapatkan keduanya sekaligus menggunakan fungsi `eig` dari modul `linalg` di NumPy.

In [26]:
matrix = np.array([[1, -1, 3],
                   [1, 1, 6],
                   [3, 8, 9]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues:
 [13.55075847  0.74003145 -3.29078992]

Eigenvectors:
 [[-0.17622017 -0.96677403 -0.53373322]
 [-0.435951    0.2053623  -0.64324848]
 [-0.88254925  0.15223105  0.54896288]]


## Calculating Dot Products

Perkalian titik (*dot product*) adalah salah satu operasi paling mendasar dalam aljabar linier yang akan sering kita temui dalam machine learning. Secara matematis, untuk dua vektor $a$ dan $b$, dot product didefinisikan sebagai:
$$a \cdot b = \sum_{i=1}^{n} a_i b_i$$

Kita bisa menggunakan fungsi `dot` dari NumPy untuk menghitung perkalian ini baik antar vektor maupun antar matriks.

In [25]:
vector_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
dot_product = np.dot(vector_a, vector_b)

print("Vektor A:", vector_a)
print("Vektor B:", vector_b)
print("\nHasil Dot Product:", dot_product)

Vektor A: [1 2 3]
Vektor B: [4 5 6]

Hasil Dot Product: 32


## Adding and Subtracting Matrices

Untuk menjumlahkan atau mengurangkan dua matriks, kita harus memastikan bahwa keduanya memiliki dimensi yang sama. NumPy memungkinkan kita untuk melakukan operasi ini secara elemen demi elemen (element-wise). Kita bisa menggunakan fungsi `np.add()` dan `np.subtract()`, atau cukup menggunakan operator matematika standar `+` dan `-` agar kode kita terlihat lebih bersih.

In [24]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])
matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

print("Hasil Penjumlahan Matriks:\n", np.add(matrix_a, matrix_b))
print("\nHasil Pengurangan Matriks:\n", matrix_a - matrix_b)

Hasil Penjumlahan Matriks:
 [[ 2  4  2]
 [ 2  4  2]
 [ 2  4 10]]

Hasil Pengurangan Matriks:
 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0 -2 -6]]


## Multiplying Matrices

Untuk mengalikan dua matriks, kita tidak menggunakan operator bintang (`*`) karena itu hanya akan mengalikan elemen di posisi yang sama. Perkalian matriks yang sesungguhnya harus mengikuti kaidah aljabar linier, di mana jumlah kolom pada matriks pertama harus sama dengan jumlah baris pada matriks kedua. Di NumPy, kita bisa menggunakan fungsi `dot` atau operator `@` yang lebih modern untuk melakukan operasi ini.

In [23]:
matrix_a = np.array([[1, 1],
                     [1, 2]])
matrix_b = np.array([[1, 3],
                     [1, 2]])
result = np.dot(matrix_a, matrix_b)

print("Hasil Perkalian Matriks (dot):\n", result)
print("\nHasil Perkalian Matriks (@):\n", matrix_a @ matrix_b)

Hasil Perkalian Matriks (dot):
 [[2 5]
 [3 7]]

Hasil Perkalian Matriks (@):
 [[2 5]
 [3 7]]


## Inverting a Matrix

Invers dari sebuah matriks persegi adalah matriks lain yang jika dikalikan dengan matriks aslinya akan menghasilkan matriks identitas. Kita sering menggunakan operasi ini untuk memecahkan berbagai persoalan matematika yang kompleks dalam machine learning. Di NumPy, kita bisa menghitung invers dengan mudah menggunakan fungsi `inv` dari modul `linalg`. Namun, perlu kita ingat bahwa hanya matriks persegi yang memiliki determinan tidak nol yang bisa di-invers.

In [32]:
matrix = np.array([[1, 4],
                   [2, 5]])
matrix_inverse = np.linalg.inv(matrix)

print("Matriks Asli:\n", matrix)
print("\nInvers Matriks:\n", matrix_inverse)
print("\nHasil Perkalian Matriks dengan Inversnya (Identitas):\n", matrix @ matrix_inverse)

Matriks Asli:
 [[1 4]
 [2 5]]

Invers Matriks:
 [[-1.66666667  1.33333333]
 [ 0.66666667 -0.33333333]]

Hasil Perkalian Matriks dengan Inversnya (Identitas):
 [[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]


## Generating Random Values

Dalam dunia *machine learning*, kita sering kali membutuhkan angka acak, misalnya untuk menentukan bobot awal (*initial weights*) sebuah model agar proses belajarnya bisa dimulai. NumPy menyediakan modul `random` yang sangat kuat untuk menghasilkan berbagai jenis angka acak. Kita bisa mengatur `seed` agar hasil angka acak yang keluar selalu sama setiap kali kode dijalankan, yang mana ini sangat membantu saat kita sedang melakukan *debugging* atau ingin memastikan hasil eksperimen kita bisa direplikasi oleh orang lain.

In [33]:
np.random.seed(0)

print("Tiga angka desimal acak:\n", np.random.random(3))
print("\nTiga angka bulat acak antara 1-10:\n", np.random.randint(1, 11, 3))
print("\nTiga angka dari distribusi normal:\n", np.random.normal(0.0, 1.0, 3))

Tiga angka desimal acak:
 [0.5488135  0.71518937 0.60276338]

Tiga angka bulat acak antara 1-10:
 [ 4  8 10]

Tiga angka dari distribusi normal:
 [-1.42232584  1.52006949 -0.29139398]


## Saving and Loading Arrays

Setelah kita melakukan berbagai manipulasi data yang kompleks, tentu kita tidak ingin kehilangan hasil kerja keras kita begitu saja. NumPy memudahkan kita untuk menyimpan array ke dalam file dan memuatnya kembali di lain waktu. Ini sangat berguna ketika kita ingin membagikan dataset yang sudah kita olah atau menyimpannya agar bisa digunakan kembali di proyek selanjutnya tanpa harus menjalankan ulang semua proses dari awal.

In [34]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
np.save("matriks_kita.npy", matrix)
loaded_matrix = np.load("matriks_kita.npy")

print("Matriks yang berhasil kita muat kembali:\n", loaded_matrix)

Matriks yang berhasil kita muat kembali:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
